# Generated by Django 4.1.7 on 2023-04-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_puanlari', '0002_tablecolumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='table_columns',
            field=models.ManyToManyField(blank=True, to='robot_puanlari.tablecolumn'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='robot_id',
            field=models.CharField(max_length=255),
        ),
    ]
