# Generated by Django 4.1.7 on 2023-04-11 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot_puanlari', '0003_robot_table_columns_alter_robot_robot_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='table_columns',
        ),
        migrations.DeleteModel(
            name='TableColumn',
        ),
    ]
