# Generated by Django 4.1.7 on 2023-04-11 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot_puanlari', '0004_remove_robot_table_columns_delete_tablecolumn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robot',
            options={'ordering': ['score', 'time']},
        ),
    ]
