# Generated by Django 4.1.7 on 2023-04-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_puanlari', '0006_alter_robot_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='sira',
            field=models.IntegerField(default=0),
        ),
    ]
