# Generated by Django 4.1.7 on 2023-04-11 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot_puanlari', '0007_robot_sira'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='sira',
        ),
    ]
