# Generated by Django 4.1.7 on 2023-03-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ituro_event', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleSaturday',
            new_name='ScheduleTuesday',
        ),
        migrations.RenameModel(
            old_name='ScheduleThursday',
            new_name='ScheduleWednesday',
        ),
        migrations.AlterModelOptions(
            name='scheduletuesday',
            options={'verbose_name_plural': 'Sali'},
        ),
        migrations.AlterModelOptions(
            name='schedulewednesday',
            options={'verbose_name_plural': 'Carsamba'},
        ),
        migrations.DeleteModel(
            name='ScheduleFriday',
        ),
    ]
