# Generated by Django 4.1.7 on 2023-03-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotlar',
            name='kategori',
            field=models.CharField(choices=[('Çizgi İzleyen: Cumhuriyet Yolu', 'Çizgi İzleyen: Cumhuriyet Yolu'), ('Mini Sumo', 'Mini Sumo'), ('Lojistik', 'Lojistik'), ('Senaryo: Arama Kurtarma', 'Senaryo: Arama Kurtarma'), ('AlgoLAB', 'AlgoLAB '), ('Renk Seçen', 'Renk Seçen'), ('Pul Toplayan', 'Pul Toplayan'), ('Trafik', 'Trafik')], default='', max_length=300, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='siralar',
            name='current_ctgr',
            field=models.CharField(choices=[('Çizgi İzleyen: Cumhuriyet Yolu', 'Çizgi İzleyen: Cumhuriyet Yolu'), ('Mini Sumo', 'Mini Sumo'), ('Lojistik', 'Lojistik'), ('Senaryo: Arama Kurtarma', 'Senaryo: Arama Kurtarma'), ('AlgoLAB', 'AlgoLAB '), ('Renk Seçen', 'Renk Seçen'), ('Pul Toplayan', 'Pul Toplayan'), ('Trafik', 'Trafik')], default='', max_length=250, verbose_name='Şu an oynanan kategori'),
        ),
    ]
